_target_: src.models.lightning_module.LitModule

num_classes: null

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: pytorch_metric_learning.losses.ArcFaceLoss
  num_classes: null
  embedding_size: 256

net:
  _target_: src.models.vision_model.get_vision_embedder
  name: vit_small_patch32_224_in21k
  embed_size: 256
