train:
  _target_: torchvision.transforms.Compose
  transforms:
   - _target_: torchvision.transforms.Resize
   
   - _target_: imgsim.data.custom_transfroms.RandomText
   - _target_: imgsim.data.custom_transfroms.RandomCircle
   